# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.10
yarn_mappings=1.21.10+build.3
loader_version=0.18.1
loom_version=1.13-SNAPSHOT

# Mod Properties
mod_name=Keep Inventory Nerf
mod_id=keep_inventory_nerf
mod_version=1.0.2
mod_authors=uhmbyee / Mariany Pinkston
mod_description=When dying, you will lose random items from your inventory.
mod_page_url=https://www.curseforge.com/minecraft/mc-mods/keep-inventory-nerf
mod_git_url=https://github.com/marianyp/Keep-Inventory-Nerf
mod_license=ARR

maven_group=dev.mariany
archives_base_name=keep_inventory_nerf

# Dependencies
fabric_version=0.138.3+1.21.10